apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: aks-store-demo
type: Opaque
data:
  azurestorageaccountname: bmVlcHM=  # base64 encoded "neeps"
  azurestorageaccountkey: # This will be filled by the deployment script
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-blob-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-csi
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: azure-blob-volume
    volumeAttributes:
      containerName: aksstoredata
    nodeStageSecretRef:
      name: azure-storage-secret
      namespace: aks-store-demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-pvc
  namespace: aks-store-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azureblob-csi
